// export { default as Button } from './Button.vue'
// export { default as Page } from './Page.vue'
// export { default as Header } from './Header.vue'
export { default as PokemonCard } from './PokemonCard'
export { default as ImageUploader } from './ImageUploader/index.vue'
